language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - gemfiles/axlsx_2.gemfile
  - gemfiles/axlsx_3.gemfile

notifications:
  email: false
