name: Tests
on:
  push:
    branches: ['master']
  #pull_request:
  #  branches: ['*']

jobs:
  test_sqlite:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          ### TEST ALL RUBY VERSIONS, USE DEFAULT GEMFILE
          #- ruby: 2.3 ### github actions giving issues with Ruby 2.3
          - ruby: 2.4
          - ruby: 2.5
          - ruby: 2.6
          - ruby: 2.7
          - ruby: "3.0" ### must be quoted otherwise will be treated as "3" which will resolve to latest 3.x version
          - ruby: 3.1

          ### CAXLSX VERSION TESTING
          - ruby: 2.6
            gemfile: gemfiles/caxlsx.gemfile
          - ruby: 2.6
            gemfile: gemfiles/caxlsx_3.0.0.gemfile

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
    - uses: actions/checkout@v3

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true

    - name: Run tests
      run: |
        bundle exec rake
